/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package optical.forms;


import optical.db.DBClass;
import optical.db.ImageUtiltiy;
import optical.db.Messages;
import optical.db.Rules;
import optical.db.Utility;
import java.awt.Color;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author star
 */
public class BillListForm extends javax.swing.JFrame {
    DBClass db=new DBClass();
    String oldname;
    /**
     * Creates new form LoginForm
     */
    public BillListForm() {
        initComponents();
        Utility.setBackground(this, Color.WHITE);
        Utility.setBorder(this);
        ImageUtiltiy.resizeLabelImage(lblimage);
        db.fillTable(table1, "select * from Bill");
        db.enableSearch(table1, "select * from Bill", cmbfield, txtsearch);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        btnedit = new javax.swing.JButton();
        btnedit1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbfield = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        btnprint = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        btnprintPO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sales Bill Register");

        btnclose.setText("X");
        btnclose.setBackground(new java.awt.Color(255, 255, 255));
        btnclose.setContentAreaFilled(false);
        btnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclose.setOpaque(true);
        btnclose.setToolTipText("Exit from Application");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notes_32x32.png"))); // NOI18N
        lblimage.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnclose)
                    .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "BillNo", "BillDate", "TransType", "Custno", "Customer  Name", "TotalAmt", "Disc%", "DiscAmt", "GST%", "GSTAmt", "NetAmt"
            }
        ));
        jScrollPane1.setViewportView(table1);

        btnedit.setText("Modifiy Bill");
        btnedit.setBackground(new java.awt.Color(255, 51, 51));
        btnedit.setContentAreaFilled(false);
        btnedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnedit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setOpaque(true);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnedit1.setText("Remove Bill");
        btnedit1.setBackground(new java.awt.Color(255, 51, 51));
        btnedit1.setContentAreaFilled(false);
        btnedit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnedit1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnedit1.setForeground(new java.awt.Color(255, 255, 255));
        btnedit1.setOpaque(true);
        btnedit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedit1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Search");

        cmbfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BillNo", "BillDate", "CustNo", "CustName", "TransType" }));

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(255, 0, 0));
        txtsearch.setToolTipText("Please enter valid username");

        btnprint.setText("Print Sales Bill Register");
        btnprint.setBackground(new java.awt.Color(255, 51, 51));
        btnprint.setContentAreaFilled(false);
        btnprint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprint.setForeground(new java.awt.Color(255, 255, 255));
        btnprint.setOpaque(true);
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        btnnew.setText("New Bill");
        btnnew.setBackground(new java.awt.Color(255, 51, 51));
        btnnew.setContentAreaFilled(false);
        btnnew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnew.setForeground(new java.awt.Color(255, 255, 255));
        btnnew.setOpaque(true);
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btnprintPO.setText("Print Bill");
        btnprintPO.setBackground(new java.awt.Color(255, 51, 51));
        btnprintPO.setContentAreaFilled(false);
        btnprintPO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprintPO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnprintPO.setForeground(new java.awt.Color(255, 255, 255));
        btnprintPO.setOpaque(true);
        btnprintPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintPOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnnew)
                        .addGap(18, 18, 18)
                        .addComponent(btnedit)
                        .addGap(35, 35, 35)
                        .addComponent(btnedit1)
                        .addGap(37, 37, 37)
                        .addComponent(btnprint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnprintPO)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmbfield, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsearch)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnedit)
                    .addComponent(btnedit1)
                    .addComponent(btnprint)
                    .addComponent(btnnew)
                    .addComponent(btnprintPO))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // Close
        dispose(); //Close current form
    }//GEN-LAST:event_btncloseActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        //Edit Bill
        int i=table1.getSelectedRow();
        if(i!=-1){
            String billno=table1.getValueAt(i, 0)+"";
            NewBillForm f=new NewBillForm();
            f.setBillInfo(billno);
            f.setVisible(true);
        }else{
            Messages.showWarning("Please select row...", "Row is not selected");
        }
        
    }//GEN-LAST:event_btneditActionPerformed

    private void btnedit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedit1ActionPerformed
        //Delete
        int i=table1.getSelectedRow();
        if(i!=-1){
            int ans=Messages.showConfirm("Are you sure?", "Confirm Delete");
            if(ans==JOptionPane.YES_OPTION){
                String billno=table1.getValueAt(i, 0)+"";                
                db.execute("delete from Bill where BillNo=?", billno);
                db.fillTable(table1, "SELECT * from Bill");
            }
        }else{
            Messages.showError("Please select row to remove", "Row Not Selected");
        }

    }//GEN-LAST:event_btnedit1ActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // Print
        HashMap<String,Object> map=new HashMap<>();
        String cond=DBClass.pvalue;
        if(cond.equals("")){
            cond="BillNo like '%%'"; //default condition
        }
        map.put("param",cond);
        map.put("paramtitle",DBClass.pvalue );
        db.showReport("src/reports/BillReport.jrxml",map);
    }//GEN-LAST:event_btnprintActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // Bill
        NewBillForm f=new NewBillForm();
        f.setVisible(true);
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnprintPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintPOActionPerformed
        // Print a specific Bill
        int i=table1.getSelectedRow();
        if(i!=-1){
            String billno=table1.getValueAt(i, 0)+"";
            HashMap<String,Object> map=new HashMap<>();
            map.put("p1",billno);        
            db.showReport("src/reports/BillMasterReport.jrxml",map);
        }else{
            Messages.showWarning("Please select row", "Select Row");
        }
            
    }//GEN-LAST:event_btnprintPOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnedit1;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnprintPO;
    private javax.swing.JComboBox<String> cmbfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblimage;
    public static javax.swing.JTable table1;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
